# Generated by Django 5.1.7 on 2025-04-06 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('Social', 'Social'), ('Fundraising', 'Fundraising'), ('Tech Talk', 'Tech Talk')], max_length=20)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'db_table': 'Events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('lname', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=80)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'db_table': 'Locations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('university_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('number_of_students', models.IntegerField()),
            ],
            options={
                'db_table': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=80, unique=True)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('Student', 'Student')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.events')),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='lname',
            field=models.ForeignKey(db_column='lname', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.locations'),
        ),
        migrations.CreateModel(
            name='RSOs',
            fields=[
                ('rso_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='inactive', max_length=10)),
                ('admin', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(db_column='university_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.universities')),
            ],
            options={
                'db_table': 'RSOs',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='university',
            field=models.ForeignKey(db_column='university_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.universities'),
        ),
        migrations.CreateModel(
            name='EventCreation',
            fields=[
                ('event', models.OneToOneField(db_column='event_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.events')),
                ('privacy', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=10)),
                ('admin', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_events', to=settings.AUTH_USER_MODEL)),
                ('superadmin', models.ForeignKey(db_column='superadmin_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='superadmin_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Event_Creation',
            },
        ),
        migrations.CreateModel(
            name='RSOEvents',
            fields=[
                ('event', models.OneToOneField(db_column='event_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.events')),
                ('rso', models.ForeignKey(db_column='rso_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.rsos')),
            ],
            options={
                'db_table': 'RSO_Events',
            },
        ),
        migrations.CreateModel(
            name='StudentsRSOs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rso', models.ForeignKey(db_column='rso_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.rsos')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Students_RSOs',
                'unique_together': {('uid', 'rso')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='events',
            unique_together={('lname', 'event_date', 'start_time')},
        ),
    ]
