# Generated by Django 5.2 on 2025-04-09 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_event_trigger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={},
        ),
        migrations.AddField(
            model_name='rsos',
            name='members',
            field=models.ManyToManyField(related_name='member_of_rsos', through='accounts.StudentsRSOs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rsos',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_of_rsos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rsos',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10),
        ),
        migrations.AlterField(
            model_name='rsos',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.universities'),
        ),
        migrations.AlterField(
            model_name='studentsrsos',
            name='rso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.rsos'),
        ),
        migrations.AlterField(
            model_name='studentsrsos',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
