# Generated by Django 5.2 on 2025-04-09 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_events_options_rsos_members_alter_rsos_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='rsos',
            name='members',
        ),
        migrations.AlterField(
            model_name='rsos',
            name='admin',
            field=models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rsos',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='inactive', max_length=10),
        ),
        migrations.AlterField(
            model_name='rsos',
            name='university',
            field=models.ForeignKey(db_column='university_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.universities'),
        ),
        migrations.AlterField(
            model_name='studentsrsos',
            name='rso',
            field=models.ForeignKey(db_column='rso_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.rsos'),
        ),
        migrations.AlterField(
            model_name='studentsrsos',
            name='uid',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
